Description:
This PR adds a custom splash screen to the Zulip app using the flutter_native_splash package. The splash screen includes:

A light blue (#ADD8E6) background.
A custom Zulip logo (assets/app-icons/zulip-combined_.png).
A fullscreen splash screen layout for a better user experience.
Android 12-specific configurations with an icon background color.
Disabled web splash screen (can be enabled later if needed).
Changes Made:
Updated pubspec.yaml
Configured flutter_native_splash settings.
Specified the image, background color, and Android 12 settings.
Ran the Splash Screen Generation Command:
sh
Copy
Edit
flutter pub run flutter_native_splash:create
This generates the required splash screen assets and updates platform-specific files.
How to Test:
Fetch the branch and run the app:
sh
Copy
Edit
flutter clean  
flutter pub get  
flutter run  
Observe the splash screen before navigating to the main app.
Screenshots:
(Attach screenshots of the splash screen on Android and iOS if possible.)

Future Improvements:
Consider adding a fade animation for a smoother transition.
Explore using a gradient background instead of a solid color.
